language: java
jdk: openjdk8

before_install: cp .travis.settings.xml $HOME/.m2/settings.xml

notifications:
  slack:
    rooms:
      secure: V5uBbw2ufVXDTs8o3cTdg/k4HCt+gYZhblQgCnfDpswHG+HhIMSEqEr1WuDrZCuNpswbCsPIoDG0ilpULzCqJFqHV6J6lQoDRbojGNt8mUTdPONaPpyKlqpdZi9NQdrZ8uI5tugfil/l8CQ1CIJYYzam/aA6MIxp8H8vr7u5kpwUa5DQ/XukNxUbLPXaNJOcTxZkdYn2CmFB0VZgmR+FcMda6yZcoLP0EgtthTKJh+pHDNsyAxN51RcoqLFd4HwdHvNjdNdDh1cgUWyOxYEESleJoJgMC3HwiZSrIeYsFBnlpTfthCLosyHyjtR3yP1xI7JZ5Nd0lN/YsTN0MR4tThnkz/6D0r7yWm3sY3znSRrmGE8HuJ6hZgufYvvr6mT5G6mA52uQ93SnI7cZTZB01Yz4LbiCWHrIs7FCWDNum9uKCkuFR6zfV7j7UIUAyH1uprd/kgfBclmS8qs1WX98hQcYj0RUyBWP6TnTXFrlxSgI2JtOD+0xMZq6+CJqUHkaILngd/ENP2PDm5FAm+dtBeY+FmuXfSmGJU72nQRMW78C3kn5fI+EmeAE1TgriJWJNH4v9qeYJHxHhd9H/3kABxHYkiv1SK/pZvd792DQ3EcOO1A7NrvtKlEDVLy/hXVZThXbZkiAYGqjZW08oNdgnTIYObeG5scBWk6RjWcffHc=
    on_failure: always
    on_success: never

cache:
  directories:
  - $HOME/.m2

branches:
    only:
        - master